export default [
  { ammount: 120.04, customerName: 'John Doe', currency: 'EUR', reference: '385' },
  { ammount: 23.0, customerName: 'Joseph Nolan', currency: 'USD', reference: '713' },
  { ammount: 1000.0, customerName: 'Paki Puckett', currency: 'EUR', reference: '356' },
  { ammount: 120.04, customerName: 'Abel Patterson', currency: 'EUR', reference: '865' },
  { ammount: 120.04, customerName: 'Lev Trevino', currency: 'EUR', reference: '264' },
  { ammount: 120.04, customerName: 'Zachery Travis', currency: 'USD', reference: '143' },
  { ammount: 120.04, customerName: 'Brenden Graves', currency: 'EUR', reference: '789' },
  { ammount: 120.04, customerName: 'Rafael Lawson', currency: 'USD', reference: '234' },
  { ammount: 120.04, customerName: 'Noble Franco', currency: 'EUR', reference: '541' },
  { ammount: 120.04, customerName: 'Luke Vega', currency: 'EUR', reference: '243' },
  { ammount: 120.04, customerName: 'Abbot Mendez', currency: 'USD', reference: '114' },
  { ammount: 120.04, customerName: 'Cyrus Gilmore', currency: 'EUR', reference: '623' },
  { ammount: 120.04, customerName: 'Walker Duffy', currency: 'EUR', reference: '778' },
  { ammount: 120.04, customerName: 'Marsden Colon', currency: 'EUR', reference: '256' },
  { ammount: 120.04, customerName: 'Demetrius Obrien', currency: 'USD', reference: '122' },
  { ammount: 120.04, customerName: 'Yoshio Oliver', currency: 'EUR', reference: '324' },
  { ammount: 120.04, customerName: 'Malcolm Jennings', currency: 'EUR', reference: '274' },
  { ammount: 120.04, customerName: 'Rashad Key', currency: 'EUR', reference: '667' },
  { ammount: 120.04, customerName: 'Malcolm Jennings', currency: 'USD', reference: '889' },
  { ammount: 120.04, customerName: 'Colton Malone', currency: 'USD', reference: '699' },
]